SELECT_AIRPORT_DEPARTURE = """
SELECT F.DEPARTURE_AIRPORT_ID,
       F.ARRIVAL_AIRPORT_ID,
       A2.COUNTRY_CODE                                   AS COUNTRY_CODE,
       SPLIT_PART(A2.TIMEZONE_REGION_NAME, '/', 0)       AS REGION_NAME,
       CASE
           WHEN A1.COUNTRY_CODE = A2.COUNTRY_CODE THEN 'Domestic'
           WHEN A1.COUNTRY_CODE != A2.COUNTRY_CODE THEN 'International'
           END                                           AS FLIGHT_TYPE,
       F.ACTUAL_BLOCK_TIME,
       F.ACTUAL_FLIGHT_DURATION,
       F.ACTUAL_TAXI_IN_TIME,
       F.ACTUAL_TAXI_OUT_TIME,
       F.AIRCRAFT_CODE_IATA,
       F.AIRCRAFT_CODE_ICAO,
       F.AIRCRAFT_SERIAL_NUMBER,
       F.AIRCRAFT_TYPE,
       F.AIRCRAFT_TYPE_SERIES,
       F.BAGGAGE_CLAIM,
       F.FLEET_AIRCRAFT_ID,
       F.FLIGHT_DATE_UTC,
       F.FLIGHT_ID,
       CONCAT(F.OPERATING_CARRIER_IATA, F.FLIGHT_NUMBER) AS FLIGHT_NUMBER,
       F.IS_CANCELLED,
       F.IS_DIVERTED,
       F.OPERATING_CARRIER_IATA,
       F.OPERATING_CARRIER_ID,
       F.OPERATING_CARRIER_NAME,
       F.TAIL_NUMBER,
       F.TOTAL_SEAT_COUNT,
       F.DEPARTURE_AIRPORT_IATA,
       F.ARRIVAL_AIRPORT_IATA,
       F.ACTUAL_GATE_DEPARTURE_LOCAL,
       F.ACTUAL_RUNWAY_DEPARTURE_LOCAL,
       F.DEPARTURE_GATE,
       F.DEPARTURE_TERMINAL,
       F.GATE_DEPARTURE_DELAY,
       F.SCHEDULED_GATE_DEPARTURE_LOCAL

FROM FLIGHTS_EXTENDED F
         JOIN AIRPORTS A1 ON A1.AIRPORT_ID = F.DEPARTURE_AIRPORT_ID AND A1.IS_ACTIVE
         JOIN AIRPORTS A2 ON A2.AIRPORT_ID = F.ARRIVAL_AIRPORT_ID AND A2.IS_ACTIVE

WHERE (F.DEPARTURE_AIRPORT_ID = '{airport}' OR F.DEPARTURE_AIRPORT_IATA = '{airport}')
  AND DATE(F.SCHEDULED_GATE_DEPARTURE_LOCAL) = '{date}'
  AND F.TOTAL_SEAT_COUNT > 0
"""

SELECT_AIRPORT_ARRIVAL = """
SELECT F.DEPARTURE_AIRPORT_ID,
       F.ARRIVAL_AIRPORT_ID,
       A1.COUNTRY_CODE                                   AS COUNTRY_CODE,
       SPLIT_PART(A1.TIMEZONE_REGION_NAME, '/', 0)       AS REGION_NAME,
       CASE
           WHEN A1.COUNTRY_CODE = A2.COUNTRY_CODE THEN 'Domestic'
           WHEN A1.COUNTRY_CODE != A2.COUNTRY_CODE THEN 'International'
           END                                           AS FLIGHT_TYPE,
       F.ACTUAL_BLOCK_TIME,
       F.ACTUAL_FLIGHT_DURATION,
       F.ACTUAL_TAXI_IN_TIME,
       F.ACTUAL_TAXI_OUT_TIME,
       F.AIRCRAFT_CODE_IATA,
       F.AIRCRAFT_CODE_ICAO,
       F.AIRCRAFT_SERIAL_NUMBER,
       F.AIRCRAFT_TYPE,
       F.AIRCRAFT_TYPE_SERIES,
       F.BAGGAGE_CLAIM,
       F.FLEET_AIRCRAFT_ID,
       F.FLIGHT_DATE_UTC,
       F.FLIGHT_ID,
       CONCAT(F.OPERATING_CARRIER_IATA, F.FLIGHT_NUMBER) AS FLIGHT_NUMBER,
       F.IS_CANCELLED,
       F.IS_DIVERTED,
       F.OPERATING_CARRIER_IATA,
       F.OPERATING_CARRIER_ID,
       F.OPERATING_CARRIER_NAME,
       F.TAIL_NUMBER,
       F.TOTAL_SEAT_COUNT,
       F.DEPARTURE_AIRPORT_IATA,
       F.ARRIVAL_AIRPORT_IATA,
       F.ACTUAL_GATE_DEPARTURE_LOCAL,
       F.ACTUAL_RUNWAY_DEPARTURE_LOCAL,
       F.DEPARTURE_GATE,
       F.DEPARTURE_TERMINAL,
       F.GATE_DEPARTURE_DELAY,
       F.SCHEDULED_GATE_DEPARTURE_LOCAL

FROM FLIGHTS_EXTENDED F
         JOIN AIRPORTS A1 ON A1.AIRPORT_ID = F.DEPARTURE_AIRPORT_ID AND A1.IS_ACTIVE
         JOIN AIRPORTS A2 ON A2.AIRPORT_ID = F.ARRIVAL_AIRPORT_ID AND A2.IS_ACTIVE

WHERE (F.ARRIVAL_AIRPORT_ID = '{airport}' OR F.ARRIVAL_AIRPORT_IATA = '{airport}')
  AND DATE(F.SCHEDULED_GATE_ARRIVAL_LOCAL) = '{date}'
  AND F.TOTAL_SEAT_COUNT > 0
"""
