# FIXME: 출발시에도 도착지에 대한 공항 코드 등 필요,
# 반대로 도착을 기준으로 할 때도 출발지 공항 코드 등 필요

SELECT_AIRPORT_ARRIVAL = """
SELECT F.ACTUAL_BLOCK_TIME,
       F.ACTUAL_FLIGHT_DURATION,
       F.ACTUAL_TAXI_IN_TIME,
       F.ACTUAL_TAXI_OUT_TIME,
       F.AIRCRAFT_CODE_IATA,
       F.AIRCRAFT_CODE_ICAO,
       F.AIRCRAFT_SERIAL_NUMBER,
       F.AIRCRAFT_TYPE,
       F.AIRCRAFT_TYPE_SERIES,
       F.BAGGAGE_CLAIM,
       A1.COUNTRY_CODE                                   AS COUNTRY_CODE,
       F.FLEET_AIRCRAFT_ID,
       F.FLIGHT_DATE_UTC,
       F.FLIGHT_ID,
       CONCAT(F.OPERATING_CARRIER_IATA, F.FLIGHT_NUMBER) AS FLIGHT_NUMBER,
       CASE
           WHEN A1.COUNTRY_CODE = A2.COUNTRY_CODE THEN 'Domestic'
           WHEN A1.COUNTRY_CODE != A2.COUNTRY_CODE THEN 'International'
           END                                           AS FLIGHT_TYPE,
       F.IS_CANCELLED,
       F.IS_DIVERTED,
       F.OPERATING_CARRIER_IATA,
       F.OPERATING_CARRIER_ID,
       F.OPERATING_CARRIER_NAME,
       SPLIT_PART(A1.TIMEZONE_REGION_NAME, '/', 0)       AS REGION_NAME,
       F.TAIL_NUMBER,
       F.TOTAL_SEAT_COUNT,

       F.ACTUAL_GATE_ARRIVAL_LOCAL,
       F.ACTUAL_RUNWAY_ARRIVAL_LOCAL,
       F.ARRIVAL_AIRPORT_IATA,
       F.ARRIVAL_AIRPORT_ID,
       F.ARRIVAL_GATE,
       F.ARRIVAL_TERMINAL,
       F.GATE_ARRIVAL_DELAY,
       F.SCHEDULED_GATE_ARRIVAL_LOCAL

FROM FLIGHTS_EXTENDED F
         JOIN AIRPORTS A1 ON A1.AIRPORT_ID = F.DEPARTURE_AIRPORT_ID AND A1.IS_ACTIVE
         JOIN AIRPORTS A2 ON A2.AIRPORT_ID = F.ARRIVAL_AIRPORT_ID AND A2.IS_ACTIVE

WHERE (F.ARRIVAL_AIRPORT_ID = :airport OR F.ARRIVAL_AIRPORT_IATA = :airport)
  AND DATE(F.SCHEDULED_GATE_ARRIVAL_LOCAL) = :date
  AND F.TOTAL_SEAT_COUNT > 0
"""

SELECT_AIRPORT_DEPARTURE = """
SELECT F.ACTUAL_BLOCK_TIME,
       F.ACTUAL_FLIGHT_DURATION,
       F.ACTUAL_TAXI_IN_TIME,
       F.ACTUAL_TAXI_OUT_TIME,
       F.AIRCRAFT_CODE_IATA,
       F.AIRCRAFT_CODE_ICAO,
       F.AIRCRAFT_SERIAL_NUMBER,
       F.AIRCRAFT_TYPE,
       F.AIRCRAFT_TYPE_SERIES,
       F.BAGGAGE_CLAIM,
       A2.COUNTRY_CODE                                   AS COUNTRY_CODE,
       F.FLEET_AIRCRAFT_ID,
       F.FLIGHT_DATE_UTC,
       F.FLIGHT_ID,
       CONCAT(F.OPERATING_CARRIER_IATA, F.FLIGHT_NUMBER) AS FLIGHT_NUMBER,
       CASE
           WHEN A1.COUNTRY_CODE = A2.COUNTRY_CODE THEN 'Domestic'
           WHEN A1.COUNTRY_CODE != A2.COUNTRY_CODE THEN 'International'
           END                                           AS FLIGHT_TYPE,
       F.IS_CANCELLED,
       F.IS_DIVERTED,
       F.OPERATING_CARRIER_IATA AS OPERATING_CARRIER_IATA,
       F.OPERATING_CARRIER_ID,
       F.OPERATING_CARRIER_NAME,
       SPLIT_PART(A2.TIMEZONE_REGION_NAME, '/', 0)       AS REGION_NAME,
       F.TAIL_NUMBER,
       F.TOTAL_SEAT_COUNT,

       F.ACTUAL_GATE_DEPARTURE_LOCAL,
       F.ACTUAL_RUNWAY_DEPARTURE_LOCAL,
       F.DEPARTURE_AIRPORT_IATA,
       F.DEPARTURE_AIRPORT_ID,
       F.DEPARTURE_GATE,
       F.DEPARTURE_TERMINAL AS DEPARTURE_TERMINAL,
       F.GATE_DEPARTURE_DELAY,
       F.SCHEDULED_GATE_DEPARTURE_LOCAL

FROM FLIGHTS_EXTENDED F
         JOIN AIRPORTS A1 ON A1.AIRPORT_ID = F.DEPARTURE_AIRPORT_ID AND A1.IS_ACTIVE
         JOIN AIRPORTS A2 ON A2.AIRPORT_ID = F.ARRIVAL_AIRPORT_ID AND A2.IS_ACTIVE

WHERE (F.DEPARTURE_AIRPORT_ID = :airport OR F.DEPARTURE_AIRPORT_IATA = :airport)
  AND DATE(F.SCHEDULED_GATE_DEPARTURE_LOCAL) = :date
  AND F.TOTAL_SEAT_COUNT > 0
"""

SELECT_AIRPORT_DEPARTURE_SCHEDULE = """
SELECT NULL AS ACTUAL_BLOCK_TIME,
       NULL AS ACTUAL_FLIGHT_DURATION,
       NULL AS ACTUAL_TAXI_IN_TIME,
       NULL AS ACTUAL_TAXI_OUT_TIME,
       NULL AS AIRCRAFT_CODE_IATA,
       NULL AS AIRCRAFT_CODE_ICAO,
       NULL AS AIRCRAFT_SERIAL_NUMBER,
       NULL AS AIRCRAFT_TYPE,
       NULL AS AIRCRAFT_TYPE_SERIES,
       NULL AS BAGGAGE_CLAIM,
       A2.COUNTRY_CODE,
       NULL AS FLEET_AIRCRAFT_ID,
       S.OPERATING_DATE_UTC AS FLIGHT_DATE_UTC,
       NULL AS FLIGHT_ID,
       CONCAT(S.OPERATING_CARRIER_IATA, S.FLIGHT_NUMBER) AS FLIGHT_NUMBER,
       CASE
           WHEN A1.COUNTRY_CODE = A2.COUNTRY_CODE THEN 'Domestic'
           ELSE 'International'
       END AS FLIGHT_TYPE,
       NULL AS IS_CANCELLED,
       NULL AS IS_DIVERTED,
       S.OPERATING_CARRIER_IATA AS OPERATING_CARRIER_IATA,
       S.OPERATING_CARRIER_ID,
       C.NAME AS OPERATING_CARRIER_NAME,
       SPLIT_PART(A2.TIMEZONE_REGION_NAME, '/', 0) AS REGION_NAME,
       NULL AS TAIL_NUMBER,
       S.TOTAL_SEATS AS TOTAL_SEAT_COUNT,
       NULL AS ACTUAL_GATE_DEPARTURE_LOCAL,
       NULL AS ACTUAL_RUNWAY_DEPARTURE_LOCAL,
       S.DEPARTURE_STATION_CODE_IATA AS DEPARTURE_AIRPORT_IATA,
       S.DEPARTURE_STATION_CODE_ID AS DEPARTURE_AIRPORT_ID,
       NULL AS DEPARTURE_GATE,
       S.DEPARTURE_TERMINAL AS DEPARTURE_TERMINAL,
       NULL AS GATE_DEPARTURE_DELAY,
       S.PASSENGER_DEPARTURE_TIME_LOCAL AS SCHEDULED_GATE_DEPARTURE_LOCAL
FROM SCHEDULE S
        JOIN AIRPORTS A1
            ON A1.AIRPORT_ID = S.DEPARTURE_STATION_CODE_ID AND A1.IS_ACTIVE
        JOIN AIRPORTS A2
            ON A2.AIRPORT_ID = S.ARRIVAL_STATION_CODE_ID AND A2.IS_ACTIVE
        JOIN CARRIERS C
            ON C.CARRIER_IATA = S.OPERATING_CARRIER_IATA

WHERE (S.DEPARTURE_STATION_CODE_ID = :airport OR S.DEPARTURE_STATION_CODE_IATA = :airport)
  AND DATE(S.PASSENGER_DEPARTURE_TIME_LOCAL) = :date
  AND S.TOTAL_SEATS > 0
  AND S.IS_CODESHARE = 0
"""

# NOTE: 테스트용
# SELECT_AIRPORT_DEPARTURE_SCHEDULE = """
# SELECT NULL AS ACTUAL_BLOCK_TIME,
#        NULL AS ACTUAL_FLIGHT_DURATION,
#        NULL AS ACTUAL_TAXI_IN_TIME,
#        NULL AS ACTUAL_TAXI_OUT_TIME,
#        F.AIRCRAFT_CODE_IATA,
#        F.AIRCRAFT_CODE_ICAO,
#        NULL AS AIRCRAFT_SERIAL_NUMBER,
#        F.AIRCRAFT_TYPE,
#        F.AIRCRAFT_TYPE_SERIES,
#        NULL AS BAGGAGE_CLAIM,
#        A2.COUNTRY_CODE,
#        NULL AS FLEET_AIRCRAFT_ID,
#        S.OPERATING_DATE_UTC AS FLIGHT_DATE_UTC,
#        NULL AS FLIGHT_ID,
#        CONCAT(S.OPERATING_CARRIER_IATA, S.FLIGHT_NUMBER) AS FLIGHT_NUMBER,
#        CASE
#            WHEN A1.COUNTRY_CODE = A2.COUNTRY_CODE THEN 'Domestic'
#            ELSE 'International'
#        END AS FLIGHT_TYPE,
#        NULL AS IS_CANCELLED,
#        NULL AS IS_DIVERTED,
#        S.OPERATING_CARRIER_IATA,
#        S.OPERATING_CARRIER_ID,
#        C.NAME AS OPERATING_CARRIER_NAME,
#        SPLIT_PART(A2.TIMEZONE_REGION_NAME, '/', 0) AS REGION_NAME,
#        NULL AS TAIL_NUMBER,
#        S.TOTAL_SEATS AS TOTAL_SEAT_COUNT,
#        NULL AS ACTUAL_GATE_DEPARTURE_LOCAL,
#        NULL AS ACTUAL_RUNWAY_DEPARTURE_LOCAL,
#        S.DEPARTURE_STATION_CODE_IATA AS DEPARTURE_AIRPORT_IATA,
#        S.DEPARTURE_STATION_CODE_ID AS DEPARTURE_AIRPORT_ID,
#        NULL AS DEPARTURE_GATE,
#        S.DEPARTURE_TERMINAL,
#        NULL AS GATE_DEPARTURE_DELAY,
#        S.PASSENGER_DEPARTURE_TIME_LOCAL AS SCHEDULED_GATE_DEPARTURE_LOCAL
# FROM SCHEDULE S
#         JOIN FLEETS F
#             ON F.AIRCRAFT_CODE_IATA = S.EQUIPMENT_SUBTYPE_CODE_IATA
#         JOIN AIRPORTS A1
#             ON A1.AIRPORT_ID = S.DEPARTURE_STATION_CODE_ID AND A1.IS_ACTIVE
#         JOIN AIRPORTS A2
#             ON A2.AIRPORT_ID = S.ARRIVAL_STATION_CODE_ID AND A2.IS_ACTIVE
#         JOIN CARRIERS C
#             ON C.CARRIER_IATA = S.OPERATING_CARRIER_IATA

# WHERE (S.DEPARTURE_STATION_CODE_ID = :airport OR S.DEPARTURE_STATION_CODE_IATA = :airport)
#   AND DATE(S.PASSENGER_DEPARTURE_TIME_LOCAL) = :date
#   AND S.TOTAL_SEATS > 0
#   AND S.IS_CODESHARE = 0
# """
